### ISSUE TITLE
Depth map multiplied by alpha values

### ISSUE THREAD

**Issue by DogeSquad** [slothfulxtx/diff-gaussian-rasterization#13]
Hi there,

I have noticed that the output depth map is somehow multiplied by the alpha values. Am I missing something or is this not intentional? Because fading out the depth via the alpha values pushes pixels closer to the camera.

![Screenshot from 2024-06-24 15-29-33](https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/73945285/ef254a6b-7b59-4640-82f2-97d673371a97)

On the left is the original depth map. On the right is the corrected depth map (division by alpha values).

**Comment by slothfulxtx** [comment]
Hi, 
My advice on the depth map is that you should regularize the output alpha map with a ground truth object mask during training, and directly use the output depth map instead of the normalized one. Maybe this solution can help.

**Comment by 2019213039** [comment]
Hello, thanks for open source.
What is the rendered alpha image used for?

Here are the original image:
![000085](https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/73419080/8a665fe0-9530-4317-aa40-517e0d61f08a)

Here are the mask:
![000085 png](https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/73419080/2dff56b1-9cd8-40af-a6d6-46b5b858e96c)


Here are the depth label:
![000085](https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/73419080/a042c4d8-bb47-4076-8ca9-1da541fdd06e)
Here are the depth results I got when training on the waymo dataset:
![00085_depth](https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/73419080/bf84deac-4a9e-450c-be55-89bb881319af)

Here are the alpha result:
![00085_alpha](https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/73419080/97c3c46a-6a45-41f4-8a89-4544a6a3d190)

From the rendered depth map, the odd thing is that for the close up white Land Rover, the rendered result sets the distance of the vehicle to the farthest distance ([1.0, 1.0, 1.0]).
Can you tell me why?

**Comment by slothfulxtx** [comment]
Sorry for the delayed response. It's quite interesting that your depth map is highly related to the semantic information of the rendered image. My advice is that use your gt depth and gt mask to supervise the 3D GS during optimization. Setting the weight of depth loss and alpha loss as 1.0 may be helpful.  @2019213039 Further discussion can be sent to my email (xutx21@mails.tsinghua.edu.cn), in which way I can see your message timely.
