### ISSUE TITLE
about extra and extra_attrs

### ISSUE THREAD

**Issue by Zerui-Yu** [slothfulxtx/diff-gaussian-rasterization#16]
感谢您的开源！浏览代码后我发现其中包括一个extra与extra_attrs
![image](https://github.com/user-attachments/assets/621e350c-3ea5-486b-bbe9-0679a1a9e1d3)
请问一下这是用户可以在Python端自定义的，用于alpha-blending的变量吗？

**Comment by slothfulxtx** [comment]
是的，这俩是一个东西
