### ISSUE TITLE
the meaning of the rendered alpha

### ISSUE THREAD

**Issue by tuning12** [slothfulxtx/diff-gaussian-rasterization#19]
Hi, thank you for your great work! What is the formula for calculating rendered alpha and what kind of physical meaning does it have?

**Comment by slothfulxtx** [comment]
@tuning12 The alpha value at pixel $p$ is defined as the sum of weight coefficients during alpha-blending based shading process. You can find the physical meaning of alpha map in [NeRF](https://arxiv.org/pdf/2003.08934).
