### ISSUE TITLE
Parallel computing may cause some issues during computing the gradient of viewmatrix

### ISSUE THREAD

**Issue by albertxwz** [slothfulxtx/diff-gaussian-rasterization#21]
I believe that the reading and writing shared data across the cuda kernel should be cautious in parallel computing. dL_dviewmatrix is shared across the cuda kernel. What you wrote is something like

```python
  dL_dviewmatrix[2] += m.x * dL_ddepth[idx];
  dL_dviewmatrix[6] += m.y * dL_ddepth[idx];
  dL_dviewmatrix[10] += m.z * dL_ddepth[idx];
  dL_dviewmatrix[14] += dL_ddepth[idx];
  dL_dviewmatrix[3] += (- m.x * mul3) * dL_ddepth[idx];
  dL_dviewmatrix[7] += (- m.y * mul3) * dL_ddepth[idx];
  dL_dviewmatrix[11] += (- m.z * mul3) * dL_ddepth[idx];
  dL_dviewmatrix[15] += (- mul3) * dL_ddepth[idx];
``` 
This may cause inconsistency of reading and writing the data and obtain unexpected results. AtomicAdd should be used in this case. However, this may degrade the performance of rendering. A better solution might be sum them up outside the cuda kernel.

**Comment by slothfulxtx** [comment]
Thanks for your suggestion, I'll check it carefully.

**Comment by slothfulxtx** [comment]
After double checking, I agree with your opinion and fix this bug, by sacrificing cuda memory space for avoiding time bottleneck. Thanks! I donot fully validate the pose branch due to lack of suitable downstream applications. If you find more bugs in my code, just leave a issue here!
