### ISSUE TITLE
Indexes of  visible gaussians from Specific Viewpoints

### ISSUE THREAD

**Issue by weiqi-zhang** [slothfulxtx/diff-gaussian-rasterization#22]
How can I get Indexes of  visible gaussians from Specific Viewpoints?

**Comment by slothfulxtx** [comment]
Hi @weiqi-zhang , considering the implementation of 3D GS splatting, you can simply backward the gradient from the rendered image to the color of 3D-GS, and then check whether the gradients of color attributes are non-zero.
