### ISSUE TITLE
Creating Gaussian Surfels

### ISSUE THREAD

**Issue by aloma85** [slothfulxtx/diff-gaussian-rasterization#24]
Hello I'm looking to create surfels with your rasterization implementation. So I set to zero the z component of the Scaling matrix in both computeCov3D in forward.cu and backward.cu. Any tips on what edits to make to get accurate rendered normals after this edit?

Also, what in which position should I put norm3Ds_precomp if I have it here:

`rendered_image, rendered_depth, rendered_norm, rendered_alpha, radii, extra = rasterizer(
    means3D = means3D,
    means2D = means2D,
    shs = shs,
    colors_precomp = colors_precomp,
    opacities = opacity,
    scales = scales,
    rotations = rotations,
    cov3Ds_precomp = cov3D_precomp,
    extra_attrs = extra_attrs
)`

**Comment by slothfulxtx** [comment]
Hi, my suggestion is to leave the cov3Ds_precomp as None, and then set the z component of the scaling matrix as a minimum value (e.g. 1e-20). You will obtain the equivalent outputs.

**Comment by aloma85** [comment]
So the normal vectors will be relatively correct if I set the z component of the scaling matrix to 1e-20? Just confirming.

**Comment by slothfulxtx** [comment]
yes, we compute the normal by comparing three scaling value and then choosing the minimal one as the shortest axis

**Comment by aloma85** [comment]
Ok I don't change the z component of scaling matrix in computeNorm3D() right? Also, If you don't mind, I'm writing a paper and your code is important to it. I have some in-depth technical questions for you. 

If you don't mind, can you email me at idrisun22@gmail(dot)com
