### ISSUE TITLE
About the pose optimize

### ISSUE THREAD

**Issue by yaokxx** [slothfulxtx/diff-gaussian-rasterization#25]
Thanks for your code! I am finding some project which use camera pose optimization. While reading the code of your pose branch, I have some doubts, I think the pose should not be the size of P, 4, 4? Because a view should share the same pose and not based on the number of gaussians? How is this aspect designed?

**Comment by slothfulxtx** [comment]
yes, the pose should be share for all 3d gaussians. however, during implementing the parallel gradient backward procress, each 3d gaussians make contribution to the camera pose. to avoid writing conflicts, we create per-gaussian array to save this part, as mentioned here. https://github.com/slothfulxtx/diff-gaussian-rasterization/issues/21

finally, the array are aggregated into 4*4 shape.
