### ISSUE TITLE
Gradient propagation in backward

### ISSUE THREAD

**Issue by git6660** [slothfulxtx/diff-gaussian-rasterization#26]
Hello, have you implemented the normal & depth gradient propagation in backpropagation (backward)?
( eg. Can I calculate the loss between ground truth normal and rendered normal，and then optimize the Gaussians through your diff-gaussian-rasterization? )

**Comment by slothfulxtx** [comment]
Sure, i've supported both the forward and backpropagation process of computing normal and depth.

**Comment by git6660** [comment]
Get it, Thanks for your reply.
