### ISSUE TITLE
About Mask

### ISSUE THREAD

**Issue by jhonnybhoo** [slothfulxtx/diff-gaussian-rasterization#3]
Hello, for alpha mask isn't this the equation

$$
\text{CumulativeOpacity} = \sum_{k=1}^{N} \alpha_i \cdot T_i
$$

 However, the code is different https://github.com/slothfulxtx/diff-gaussian-rasterization/blob/main/cuda_rasterizer/forward.cu#L372
 in that only account for $T$ why not $\alpha_i$? Maybe I am confused what is alpha mask? (1 indicates opaque and 0 indicates transparent?)

**Comment by JohnsonLC** [comment]
Because $T$ actually is the rested opacity (1 - cumulative opacity).
