### ISSUE TITLE
Question about renderCUDA

### ISSUE THREAD

**Issue by zhanglk9** [slothfulxtx/diff-gaussian-rasterization#4]
Thanks for your great job!
I want to know why added the `accum_rea = last_alpha + (1.f - last_alpha) * accum_rea;
			dL_dalpha += (1 - accum_rea) * dL_dpixel_alpha;` in renderCUDA `backward.cu` You know that in the gaussian-splatting's code ,this isn't be added. and how can I get the formula about this part.

**Comment by slothfulxtx** [comment]
Hi, 
  We wanna support the gradient back-propagation of alpha map supervision. Sometimes we have the ground truth alpha map of the scene, and we may compute the l1 loss between the predicted alpha map and GT.
