### ISSUE TITLE
Just single pixel rendering

### ISSUE THREAD

**Issue by pknmax** [slothfulxtx/diff-gaussian-rasterization#5]
Hello,
Is it possible to render just single pixel which returns the color of each single ray from different colmap camera positions using depth/diff-gaussian-rasterization?

I am interested in getting final color at particular location for different view directions, by providing: 3DGS pointcloud, colmap camera poses, "location of target pixel for tracking in first fully rasterized image using first colmap camera pose from colmap pose sequence" or "3D location in scene (how to find it?)".
Can you please guide me to achieve this?

**Comment by pknmax** [comment]
@slothfulxtx any suggestions please?

**Comment by slothfulxtx** [comment]
Hi,
  Sorry for the delayed response. Do you mean some work similar to pixelNerf ? From my perspective, it's quite hard to dig into the rendering process of one pixel and interact with each gaussians compared with nerf. One pixel may interact with thousands of gaussians on CUDA device during rendering, which limits the GPU memory and computational cost you can consume. On the other side, nerf fixes the number of sample points per rays and explicitly compute it in python env. Thus it's easier to interact with these locations for futher computation.

**Comment by pknmax** [comment]
Actually, I just want to know a final pixel color for known 3D location in screen space.
Basically, how to blend gaussians for particular single pixel location?

Suppose I have trained gaussian splatting point cloud (ply file), which is trained on sufficient multiview images; then how I can find a final color after blending of gaussians responsible for particular 3D location after projecting it into screen space for particular colmap camera pose? Also, how can we get color of that particular location from various colmap camera poses (basically tracking that 3D location in screen space)? 

e.g. I want to find a color of pixel at blue dot from different colmap camera poses?
![image](https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/152391989/541dcca0-8d7e-4b66-b649-fe3aa3291ebd)

**Comment by slothfulxtx** [comment]
Hi,
Sorry for the delayed response. Do you want to find 3D Gaussians which contributes to the final color of a specific pixel under a specific camera pose? You can simply backward the gradient of this pixel and then search for 3D Gaussians whose color gradients are not zero.

**Comment by z1V-Chan** [comment]
Gaussian Opacity Field could be what u want maybe...

**Comment by prakashknaikade** [comment]
@z1V-Chan how I can do it with Gaussian Opacity Field (https://github.com/autonomousvision/gaussian-opacity-fields)?
can you please elaborate?

**Comment by pknmax** [comment]
@z1V-Chan how I can do it with Gaussian Opacity Field (https://github.com/autonomousvision/gaussian-opacity-fields)?
can you please elaborate?

**Comment by z1V-Chan** [comment]
> @z1V-Chan how I can do it with Gaussian Opacity Field (https://github.com/autonomousvision/gaussian-opacity-fields)? can you please elaborate?

I can't tell it exactly since I have not checked the code yet while the paper showed that the pixel could be rendered in a similar way to NeRF, which is in the chapter 3.1 in the paper.
