### ISSUE TITLE
what are possible application and use of rendered_depth & rendered_alpha?

### ISSUE THREAD

**Issue by pknmax** [slothfulxtx/diff-gaussian-rasterization#6]
1. does this make trained scene representation/ rendering better than original 3DGS rasterizer?
2. is there a way to use this to make loss term used in 3DGS more efficient and better?

**Comment by slothfulxtx** [comment]
Hi,
If you regularize the 3D GS with additional outputs during training, such as ground truth foreground masks or depth maps, you can obtain a better 3D representation from multiview inputs. The computation of depth maps and alpha maps consumes additional time cost for rendering, thus the original rendering process is a bit more efficient than our implementation.

**Comment by prakashknaikade** [comment]
But most of the times we do not have ground truth foreground masks or depth maps, then how can we use computed depth maps and alpha maps? Can you please point out to some work?

**Comment by slothfulxtx** [comment]
For example, if you wanna reconstruct the object surface from multi-view input, you should segment the target object from the background. Thus, you can adopt segment anything or other semantic segmentation tools to achieve this, and then consider it as a additional supervision of 3D-GS alpha mask. (SuGAR, 2D-GS, and other works trained on DTU dataset) For the predicted depth maps, sometimes you wanna obtain a smooth surface of the reconstructed scene, which is important for sparse-view reconstruction to reduce floaters during training, you can adopt addition regularization using the depth maps to achieve this goal. (Any sparse-view gaussian splatting paper)
