### ISSUE TITLE
the range of `colors_precomp`

### ISSUE THREAD

**Issue by raynehe** [slothfulxtx/diff-gaussian-rasterization#8]
Hello, thanks for the wonderful work!

I have a question regarding the range of the parameter `colors_precomp`. I have a `color_raw` which ranges from 0 to 300. When I clamp it using:
```python
color = torch.clamp(color_raw, 0.0, 256.)
out = rasterizer(
          means3D = means3D,
          means2D = means2D,
          shs = None,
          colors_precomp = color,
          opacities = ones,
          scales = scales,
          rotations = rotations,
          cov3D_precomp = None)[0]
```
I get a more white image, compared with:
```python
color = torch.clamp(color_raw, 0.0, 1.)
```

I'm wondering would this function clamp the `colors_precomp` between 0-1? If yes, why does it get a more white image when clamping this term using a wider range?

I hope you could give me a hint about it. Thank you very much!

**Comment by slothfulxtx** [comment]
Hi,
thanks for your interest! We suppose all rgb value lying in the range [0,1], thus tranform your `colors_precomp` into this range with scaling maybe the simplest solution. Sorry i donot get your point on "more white image". I think there may be some incorrect configuration of the `bg` color in `GaussianRasterizationSettings`.
