### ISSUE TITLE
unexpected keyword argument 'cov3D_precomp'

### ISSUE THREAD

**Issue by huizhizhao** [slothfulxtx/diff-gaussian-rasterization#9]
Thanks for the great work, I ran into a problem while using it. I use it as follows

 rendered_image, rendered_depth, rendered_norm, rendered_alpha, radii, extra = rasterizer(
        means3D=pts_xyz,
        means2D=screenspace_points,
        shs=None,
        colors_precomp=pts_rgb,
        opacities=opacity,
        scales=scales,
        rotations=rotations,
        cov3D_precomp=None,
        extra_attrs = pts_rgb)

Exception has occurred: TypeError
GaussianRasterizer.forward() got an unexpected keyword argument 'cov3D_precomp'

If I remove the ‘cov3D_precomp’ parameter and don't pass in the function, it works fine. why?

**Comment by slothfulxtx** [comment]
Hi,
we rename the `cov3D_precomp` as `cov3Ds_precomp`, following the naming rules of other arguments in the function. You can just ignore this argument during function call because we need `scales` and `rotations` to compute normal maps.
